// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt53ZeL831fsalc7ICHeZgPsVHM4M0fwU',
    appId: '1:273347061023:web:3408517882880c72dd7c2a',
    messagingSenderId: '273347061023',
    projectId: 'fbproject-c8fa9',
    authDomain: 'fbproject-c8fa9.firebaseapp.com',
    storageBucket: 'fbproject-c8fa9.firebasestorage.app',
    measurementId: 'G-262RJNJ687',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVUI9AJjj68TRqmbeGPBsfY34kHZrzu4Q',
    appId: '1:273347061023:android:89cfecd5bc2ac9c9dd7c2a',
    messagingSenderId: '273347061023',
    projectId: 'fbproject-c8fa9',
    storageBucket: 'fbproject-c8fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDun_fTi4i4-WQvMzHv6v74D2juwEPInL8',
    appId: '1:273347061023:ios:e816e1244e93d845dd7c2a',
    messagingSenderId: '273347061023',
    projectId: 'fbproject-c8fa9',
    storageBucket: 'fbproject-c8fa9.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );
}
